accounts:
  - name: alice
    coins: ["100000token", "200000000stake"]
  - name: bob
    coins: ["100000token", "100000000stake"]
  - name: kashyap
    coins: ["0token", "100000000stake"]

validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"

nameservice:
  address: cosmos1ukgzuyrq2fqwccsld3m45f38897fsm4hamg3vz

faucet:
  name: bob
  coins: ["5token", "100000stake"]

build:
  binary: "kashyap"
